# example from: https://github.com/organizations/unicorn-os/settings/actions/runners/new

# Download
- name: Make Directory
  ansible.builtin.file:
    path: "{{home}}/actions-runner"
    state: directory

- name: Download
  ansible.builtin.get_url:
    url: "{{latest_url}}"
    dest: "{{home}}/actions-runner/{{file_name}}"

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: "{{home}}/actions-runner/{{file_name}}"
    dest: "{{home}}/actions-runner/"
    keep_newer: true
    remote_src: yes


# Configure
- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: unattended.sh.j2
    dest: "{{home}}/actions-runner/unattended.sh"
    mode: '0744'

- debug:
    msg: "Uses unattended setup by default. Set `unnatended: false` if you need to make changes!"

- name: Create the runner and start the configuration experience
  ansible.builtin.shell: "./unattended.sh"
  args:
    chdir: "{{home}}/actions-runner"
    creates: my.sh
  when: unattended
  become: true
