# example from: https://github.com/organizations/unicorn-os/settings/actions/runners/new

# Download
- name: Make Directory
  ansible.builtin.file:
    path: "{{home}}/actions-runner"
    state: directory

- name: Download
  ansible.builtin.get_url:
    url: "{{latest_url}}"
    dest: "{{home}}/actions-runner/{{file_name}}"

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: "{{home}}/actions-runner/{{file_name}}"
    dest: "{{home}}/actions-runner/"
    remote_src: yes

- debug:
    msg: "TODO! This need to be made automated. Currently `config.sh` requires manual input!"

# Configure
- name: Create the runner and start the configuration experience
  # ansible.builtin.shell: "./config.sh --url https://github.com/MetaBotAI --token {{token}}"
  ansible.builtin.shell: "echo './config.sh --url https://github.com/MetaBotAI --token {{token}}' >run.sh ; chmod +x run.sh"
  args:
    chdir: "{{home}}/actions-runner"
    creates: run.sh